/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GoalRequest,
  GoalResponse,
  HTTPValidationError,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getGoalApiV1GoalsGetResponse200 = {
  data: GoalResponse | null;
  status: 200;
};

export type getGoalApiV1GoalsGetResponseSuccess =
  getGoalApiV1GoalsGetResponse200 & {
    headers: Headers;
  };
export type getGoalApiV1GoalsGetResponse = getGoalApiV1GoalsGetResponseSuccess;

export const getGetGoalApiV1GoalsGetUrl = () => {
  return `/api/v1/goals`;
};

/**
 * Get user's goal.
 * @summary Get Goal
 */
export const getGoalApiV1GoalsGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getGoalApiV1GoalsGetResponse> => {
  return customFetch<getGoalApiV1GoalsGetResponse>(
    getGetGoalApiV1GoalsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetGoalApiV1GoalsGetQueryKey = () => {
  return [`/api/v1/goals`] as const;
};

export const getGetGoalApiV1GoalsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGoalApiV1GoalsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>
  > = ({ signal }) => getGoalApiV1GoalsGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGoalApiV1GoalsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>
>;
export type GetGoalApiV1GoalsGetQueryError = unknown;

export function useGetGoalApiV1GoalsGet<
  TData = Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
          TError,
          Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoalApiV1GoalsGet<
  TData = Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
          TError,
          Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoalApiV1GoalsGet<
  TData = Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Goal
 */

export function useGetGoalApiV1GoalsGet<
  TData = Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGoalApiV1GoalsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGoalApiV1GoalsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createGoalApiV1GoalsPostResponse200 = {
  data: GoalResponse;
  status: 200;
};

export type createGoalApiV1GoalsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createGoalApiV1GoalsPostResponseSuccess =
  createGoalApiV1GoalsPostResponse200 & {
    headers: Headers;
  };
export type createGoalApiV1GoalsPostResponseError =
  createGoalApiV1GoalsPostResponse422 & {
    headers: Headers;
  };

export type createGoalApiV1GoalsPostResponse =
  | createGoalApiV1GoalsPostResponseSuccess
  | createGoalApiV1GoalsPostResponseError;

export const getCreateGoalApiV1GoalsPostUrl = () => {
  return `/api/v1/goals`;
};

/**
 * Create a new goal.
 * @summary Create Goal
 */
export const createGoalApiV1GoalsPost = async (
  goalRequest: GoalRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<createGoalApiV1GoalsPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<createGoalApiV1GoalsPostResponse>(
    getCreateGoalApiV1GoalsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(goalRequest),
    },
  );
};

export const getCreateGoalApiV1GoalsPostMutationKey = () =>
  ["createGoalApiV1GoalsPost"] as const;

export const getCreateGoalApiV1GoalsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>,
    TError,
    CreateGoalApiV1GoalsPostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>,
  TError,
  CreateGoalApiV1GoalsPostMutationVariables,
  TContext
> => {
  const mutationKey = getCreateGoalApiV1GoalsPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>,
    CreateGoalApiV1GoalsPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createGoalApiV1GoalsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateGoalApiV1GoalsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>
>;
export type CreateGoalApiV1GoalsPostMutationBody = GoalRequest;
export type CreateGoalApiV1GoalsPostMutationError = HTTPValidationError;
export type CreateGoalApiV1GoalsPostMutationVariables = { data: GoalRequest };

/**
 * @summary Create Goal
 */
export const useCreateGoalApiV1GoalsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>,
      TError,
      CreateGoalApiV1GoalsPostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createGoalApiV1GoalsPost>>,
  TError,
  CreateGoalApiV1GoalsPostMutationVariables,
  TContext
> => {
  return useMutation(
    getCreateGoalApiV1GoalsPostMutationOptions(options),
    queryClient,
  );
};
export type updateGoalApiV1GoalsPatchResponse200 = {
  data: GoalResponse;
  status: 200;
};

export type updateGoalApiV1GoalsPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateGoalApiV1GoalsPatchResponseSuccess =
  updateGoalApiV1GoalsPatchResponse200 & {
    headers: Headers;
  };
export type updateGoalApiV1GoalsPatchResponseError =
  updateGoalApiV1GoalsPatchResponse422 & {
    headers: Headers;
  };

export type updateGoalApiV1GoalsPatchResponse =
  | updateGoalApiV1GoalsPatchResponseSuccess
  | updateGoalApiV1GoalsPatchResponseError;

export const getUpdateGoalApiV1GoalsPatchUrl = () => {
  return `/api/v1/goals`;
};

/**
 * Update user's goal.
 * @summary Update Goal
 */
export const updateGoalApiV1GoalsPatch = async (
  goalRequest: GoalRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<updateGoalApiV1GoalsPatchResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<updateGoalApiV1GoalsPatchResponse>(
    getUpdateGoalApiV1GoalsPatchUrl(),
    {
      ...options,
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(goalRequest),
    },
  );
};

export const getUpdateGoalApiV1GoalsPatchMutationKey = () =>
  ["updateGoalApiV1GoalsPatch"] as const;

export const getUpdateGoalApiV1GoalsPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>,
    TError,
    UpdateGoalApiV1GoalsPatchMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>,
  TError,
  UpdateGoalApiV1GoalsPatchMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateGoalApiV1GoalsPatchMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>,
    UpdateGoalApiV1GoalsPatchMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return updateGoalApiV1GoalsPatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGoalApiV1GoalsPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>
>;
export type UpdateGoalApiV1GoalsPatchMutationBody = GoalRequest;
export type UpdateGoalApiV1GoalsPatchMutationError = HTTPValidationError;
export type UpdateGoalApiV1GoalsPatchMutationVariables = { data: GoalRequest };

/**
 * @summary Update Goal
 */
export const useUpdateGoalApiV1GoalsPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>,
      TError,
      UpdateGoalApiV1GoalsPatchMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateGoalApiV1GoalsPatch>>,
  TError,
  UpdateGoalApiV1GoalsPatchMutationVariables,
  TContext
> => {
  return useMutation(
    getUpdateGoalApiV1GoalsPatchMutationOptions(options),
    queryClient,
  );
};
