/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  EstimateQueuedResponse,
  EstimateResponse,
  HTTPValidationError,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse200 = {
  data: EstimateQueuedResponse;
  status: 200;
};

export type estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type estimatePhotoApiV1PhotosPhotoIdEstimatePostResponseSuccess =
  estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse200 & {
    headers: Headers;
  };
export type estimatePhotoApiV1PhotosPhotoIdEstimatePostResponseError =
  estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse422 & {
    headers: Headers;
  };

export type estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse =
  | estimatePhotoApiV1PhotosPhotoIdEstimatePostResponseSuccess
  | estimatePhotoApiV1PhotosPhotoIdEstimatePostResponseError;

export const getEstimatePhotoApiV1PhotosPhotoIdEstimatePostUrl = (
  photoId: string,
) => {
  return `/api/v1/photos/${photoId}/estimate`;
};

/**
 * @summary Estimate Photo
 */
export const estimatePhotoApiV1PhotosPhotoIdEstimatePost = async (
  photoId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse> => {
  return customFetch<estimatePhotoApiV1PhotosPhotoIdEstimatePostResponse>(
    getEstimatePhotoApiV1PhotosPhotoIdEstimatePostUrl(photoId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getEstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationKey = () =>
  ["estimatePhotoApiV1PhotosPhotoIdEstimatePost"] as const;

export const getEstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>,
    TError,
    EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>,
  TError,
  EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables,
  TContext
> => {
  const mutationKey =
    getEstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>,
    EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables
  > = (props) => {
    const { photoId } = props ?? {};

    return estimatePhotoApiV1PhotosPhotoIdEstimatePost(photoId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>
  >;

export type EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationError =
  HTTPValidationError;
export type EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables = {
  photoId: string;
};

/**
 * @summary Estimate Photo
 */
export const useEstimatePhotoApiV1PhotosPhotoIdEstimatePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>,
      TError,
      EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof estimatePhotoApiV1PhotosPhotoIdEstimatePost>>,
  TError,
  EstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationVariables,
  TContext
> => {
  return useMutation(
    getEstimatePhotoApiV1PhotosPhotoIdEstimatePostMutationOptions(options),
    queryClient,
  );
};
export type getEstimateApiV1EstimatesEstimateIdGetResponse200 = {
  data: EstimateResponse;
  status: 200;
};

export type getEstimateApiV1EstimatesEstimateIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getEstimateApiV1EstimatesEstimateIdGetResponseSuccess =
  getEstimateApiV1EstimatesEstimateIdGetResponse200 & {
    headers: Headers;
  };
export type getEstimateApiV1EstimatesEstimateIdGetResponseError =
  getEstimateApiV1EstimatesEstimateIdGetResponse422 & {
    headers: Headers;
  };

export type getEstimateApiV1EstimatesEstimateIdGetResponse =
  | getEstimateApiV1EstimatesEstimateIdGetResponseSuccess
  | getEstimateApiV1EstimatesEstimateIdGetResponseError;

export const getGetEstimateApiV1EstimatesEstimateIdGetUrl = (
  estimateId: string,
) => {
  return `/api/v1/estimates/${estimateId}`;
};

/**
 * @summary Get Estimate
 */
export const getEstimateApiV1EstimatesEstimateIdGet = async (
  estimateId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<getEstimateApiV1EstimatesEstimateIdGetResponse> => {
  return customFetch<getEstimateApiV1EstimatesEstimateIdGetResponse>(
    getGetEstimateApiV1EstimatesEstimateIdGetUrl(estimateId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetEstimateApiV1EstimatesEstimateIdGetQueryKey = (
  estimateId: string,
) => {
  return [`/api/v1/estimates/${estimateId}`] as const;
};

export const getGetEstimateApiV1EstimatesEstimateIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
  TError = HTTPValidationError,
>(
  estimateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetEstimateApiV1EstimatesEstimateIdGetQueryKey(estimateId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>
  > = ({ signal }) =>
    getEstimateApiV1EstimatesEstimateIdGet(estimateId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: estimateId !== null && estimateId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEstimateApiV1EstimatesEstimateIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>
>;
export type GetEstimateApiV1EstimatesEstimateIdGetQueryError =
  HTTPValidationError;

export function useGetEstimateApiV1EstimatesEstimateIdGet<
  TData = Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
  TError = HTTPValidationError,
>(
  estimateId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
          TError,
          Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEstimateApiV1EstimatesEstimateIdGet<
  TData = Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
  TError = HTTPValidationError,
>(
  estimateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
          TError,
          Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEstimateApiV1EstimatesEstimateIdGet<
  TData = Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
  TError = HTTPValidationError,
>(
  estimateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Estimate
 */

export function useGetEstimateApiV1EstimatesEstimateIdGet<
  TData = Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
  TError = HTTPValidationError,
>(
  estimateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEstimateApiV1EstimatesEstimateIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEstimateApiV1EstimatesEstimateIdGetQueryOptions(
    estimateId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
