/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Health check endpoint for Fly.io.
 * @summary Healthz
 */
export type healthzHealthzGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthzHealthzGetResponseSuccess = healthzHealthzGetResponse200 & {
  headers: Headers;
};
export type healthzHealthzGetResponse = healthzHealthzGetResponseSuccess;

export const getHealthzHealthzGetUrl = () => {
  return `/healthz`;
};

export const healthzHealthzGet = async (
  options?: RequestInit,
): Promise<healthzHealthzGetResponse> => {
  return customFetch<healthzHealthzGetResponse>(getHealthzHealthzGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthzHealthzGetQueryKey = () => {
  return [`/healthz`] as const;
};

export const getHealthzHealthzGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthzHealthzGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthzHealthzGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthzHealthzGet>>
  > = ({ signal }) => healthzHealthzGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthzHealthzGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type HealthzHealthzGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthzHealthzGet>>
>;
export type HealthzHealthzGetQueryError = unknown;

export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthzHealthzGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthzHealthzGet>>,
          TError,
          Awaited<ReturnType<typeof healthzHealthzGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthzHealthzGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthzHealthzGet>>,
          TError,
          Awaited<ReturnType<typeof healthzHealthzGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthzHealthzGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Healthz
 */

export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthzHealthzGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getHealthzHealthzGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}
