services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build: .
    command: uvicorn calorie_track_ai_bot.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    env_file: [.env]
    depends_on: [redis, worker]

  worker:
    build: .
    command: python -m calorie_track_ai_bot.workers.estimate_worker
    env_file: [.env]
    depends_on: [redis]

volumes:
  redis_data:
