/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type telegramWebhookBotPostResponse200 = {
  data: unknown;
  status: 200;
};

export type telegramWebhookBotPostResponseSuccess =
  telegramWebhookBotPostResponse200 & {
    headers: Headers;
  };
export type telegramWebhookBotPostResponse =
  telegramWebhookBotPostResponseSuccess;

export const getTelegramWebhookBotPostUrl = () => {
  return `/bot`;
};

/**
 * Handle Telegram webhook updates.
 * @summary Telegram Webhook
 */
export const telegramWebhookBotPost = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<telegramWebhookBotPostResponse> => {
  return customFetch<telegramWebhookBotPostResponse>(
    getTelegramWebhookBotPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getTelegramWebhookBotPostMutationKey = () =>
  ["telegramWebhookBotPost"] as const;

export const getTelegramWebhookBotPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof telegramWebhookBotPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof telegramWebhookBotPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getTelegramWebhookBotPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof telegramWebhookBotPost>>,
    void
  > = () => {
    return telegramWebhookBotPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TelegramWebhookBotPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof telegramWebhookBotPost>>
>;

export type TelegramWebhookBotPostMutationError = unknown;

/**
 * @summary Telegram Webhook
 */
export const useTelegramWebhookBotPost = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof telegramWebhookBotPost>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof telegramWebhookBotPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getTelegramWebhookBotPostMutationOptions(options),
    queryClient,
  );
};
export type setupWebhookBotSetupPostResponse200 = {
  data: unknown;
  status: 200;
};

export type setupWebhookBotSetupPostResponseSuccess =
  setupWebhookBotSetupPostResponse200 & {
    headers: Headers;
  };
export type setupWebhookBotSetupPostResponse =
  setupWebhookBotSetupPostResponseSuccess;

export const getSetupWebhookBotSetupPostUrl = () => {
  return `/bot/setup`;
};

/**
 * Setup Telegram webhook if configured.
 * @summary Setup Webhook
 */
export const setupWebhookBotSetupPost = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<setupWebhookBotSetupPostResponse> => {
  return customFetch<setupWebhookBotSetupPostResponse>(
    getSetupWebhookBotSetupPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getSetupWebhookBotSetupPostMutationKey = () =>
  ["setupWebhookBotSetupPost"] as const;

export const getSetupWebhookBotSetupPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setupWebhookBotSetupPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setupWebhookBotSetupPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getSetupWebhookBotSetupPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setupWebhookBotSetupPost>>,
    void
  > = () => {
    return setupWebhookBotSetupPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetupWebhookBotSetupPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof setupWebhookBotSetupPost>>
>;

export type SetupWebhookBotSetupPostMutationError = unknown;

/**
 * @summary Setup Webhook
 */
export const useSetupWebhookBotSetupPost = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setupWebhookBotSetupPost>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setupWebhookBotSetupPost>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getSetupWebhookBotSetupPostMutationOptions(options),
    queryClient,
  );
};
export type getWebhookInfoBotWebhookInfoGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getWebhookInfoBotWebhookInfoGetResponseSuccess =
  getWebhookInfoBotWebhookInfoGetResponse200 & {
    headers: Headers;
  };
export type getWebhookInfoBotWebhookInfoGetResponse =
  getWebhookInfoBotWebhookInfoGetResponseSuccess;

export const getGetWebhookInfoBotWebhookInfoGetUrl = () => {
  return `/bot/webhook-info`;
};

/**
 * Get current webhook information.
 * @summary Get Webhook Info
 */
export const getWebhookInfoBotWebhookInfoGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getWebhookInfoBotWebhookInfoGetResponse> => {
  return customFetch<getWebhookInfoBotWebhookInfoGetResponse>(
    getGetWebhookInfoBotWebhookInfoGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetWebhookInfoBotWebhookInfoGetQueryKey = () => {
  return [`/bot/webhook-info`] as const;
};

export const getGetWebhookInfoBotWebhookInfoGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetWebhookInfoBotWebhookInfoGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>
  > = ({ signal }) =>
    getWebhookInfoBotWebhookInfoGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWebhookInfoBotWebhookInfoGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>
>;
export type GetWebhookInfoBotWebhookInfoGetQueryError = unknown;

export function useGetWebhookInfoBotWebhookInfoGet<
  TData = Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebhookInfoBotWebhookInfoGet<
  TData = Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebhookInfoBotWebhookInfoGet<
  TData = Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Webhook Info
 */

export function useGetWebhookInfoBotWebhookInfoGet<
  TData = Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWebhookInfoBotWebhookInfoGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWebhookInfoBotWebhookInfoGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type deleteWebhookBotWebhookDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteWebhookBotWebhookDeleteResponseSuccess =
  deleteWebhookBotWebhookDeleteResponse200 & {
    headers: Headers;
  };
export type deleteWebhookBotWebhookDeleteResponse =
  deleteWebhookBotWebhookDeleteResponseSuccess;

export const getDeleteWebhookBotWebhookDeleteUrl = () => {
  return `/bot/webhook`;
};

/**
 * Delete current webhook.
 * @summary Delete Webhook
 */
export const deleteWebhookBotWebhookDelete = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<deleteWebhookBotWebhookDeleteResponse> => {
  return customFetch<deleteWebhookBotWebhookDeleteResponse>(
    getDeleteWebhookBotWebhookDeleteUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteWebhookBotWebhookDeleteMutationKey = () =>
  ["deleteWebhookBotWebhookDelete"] as const;

export const getDeleteWebhookBotWebhookDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getDeleteWebhookBotWebhookDeleteMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>,
    void
  > = () => {
    return deleteWebhookBotWebhookDelete(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWebhookBotWebhookDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>
>;

export type DeleteWebhookBotWebhookDeleteMutationError = unknown;

/**
 * @summary Delete Webhook
 */
export const useDeleteWebhookBotWebhookDelete = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteWebhookBotWebhookDelete>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getDeleteWebhookBotWebhookDeleteMutationOptions(options),
    queryClient,
  );
};
