/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FeedbackSubmission,
  FeedbackSubmissionRequest,
  FeedbackSubmissionResponse,
  HTTPValidationError,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type submitFeedbackApiV1FeedbackPostResponse201 = {
  data: FeedbackSubmissionResponse;
  status: 201;
};

export type submitFeedbackApiV1FeedbackPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type submitFeedbackApiV1FeedbackPostResponseSuccess =
  submitFeedbackApiV1FeedbackPostResponse201 & {
    headers: Headers;
  };
export type submitFeedbackApiV1FeedbackPostResponseError =
  submitFeedbackApiV1FeedbackPostResponse422 & {
    headers: Headers;
  };

export type submitFeedbackApiV1FeedbackPostResponse =
  | submitFeedbackApiV1FeedbackPostResponseSuccess
  | submitFeedbackApiV1FeedbackPostResponseError;

export const getSubmitFeedbackApiV1FeedbackPostUrl = () => {
  return `/api/v1/feedback`;
};

/**
 * Submit user feedback, bug report, question, or support request.
 *
 * Stores submission in database and sends notification to admin chat/channel.
 *
 * Args:
 *     request: FastAPI request object (for auth headers)
 *     payload: Feedback submission request body
 *
 * Returns:
 *     Feedback submission response with ID and confirmation
 *
 * Raises:
 *     HTTPException: If submission fails
 * @summary Submit Feedback
 */
export const submitFeedbackApiV1FeedbackPost = async (
  feedbackSubmissionRequest: FeedbackSubmissionRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<submitFeedbackApiV1FeedbackPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<submitFeedbackApiV1FeedbackPostResponse>(
    getSubmitFeedbackApiV1FeedbackPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(feedbackSubmissionRequest),
    },
  );
};

export const getSubmitFeedbackApiV1FeedbackPostMutationKey = () =>
  ["submitFeedbackApiV1FeedbackPost"] as const;

export const getSubmitFeedbackApiV1FeedbackPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>,
    TError,
    SubmitFeedbackApiV1FeedbackPostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>,
  TError,
  SubmitFeedbackApiV1FeedbackPostMutationVariables,
  TContext
> => {
  const mutationKey = getSubmitFeedbackApiV1FeedbackPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>,
    SubmitFeedbackApiV1FeedbackPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return submitFeedbackApiV1FeedbackPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitFeedbackApiV1FeedbackPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>
>;
export type SubmitFeedbackApiV1FeedbackPostMutationBody =
  FeedbackSubmissionRequest;
export type SubmitFeedbackApiV1FeedbackPostMutationError = HTTPValidationError;
export type SubmitFeedbackApiV1FeedbackPostMutationVariables = {
  data: FeedbackSubmissionRequest;
};

/**
 * @summary Submit Feedback
 */
export const useSubmitFeedbackApiV1FeedbackPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>,
      TError,
      SubmitFeedbackApiV1FeedbackPostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitFeedbackApiV1FeedbackPost>>,
  TError,
  SubmitFeedbackApiV1FeedbackPostMutationVariables,
  TContext
> => {
  return useMutation(
    getSubmitFeedbackApiV1FeedbackPostMutationOptions(options),
    queryClient,
  );
};
export type getFeedbackApiV1FeedbackFeedbackIdGetResponse200 = {
  data: FeedbackSubmission;
  status: 200;
};

export type getFeedbackApiV1FeedbackFeedbackIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getFeedbackApiV1FeedbackFeedbackIdGetResponseSuccess =
  getFeedbackApiV1FeedbackFeedbackIdGetResponse200 & {
    headers: Headers;
  };
export type getFeedbackApiV1FeedbackFeedbackIdGetResponseError =
  getFeedbackApiV1FeedbackFeedbackIdGetResponse422 & {
    headers: Headers;
  };

export type getFeedbackApiV1FeedbackFeedbackIdGetResponse =
  | getFeedbackApiV1FeedbackFeedbackIdGetResponseSuccess
  | getFeedbackApiV1FeedbackFeedbackIdGetResponseError;

export const getGetFeedbackApiV1FeedbackFeedbackIdGetUrl = (
  feedbackId: string,
) => {
  return `/api/v1/feedback/${feedbackId}`;
};

/**
 * Get feedback submission by ID (admin only).
 *
 * Args:
 *     request: FastAPI request object (for auth)
 *     feedback_id: Feedback submission UUID
 *
 * Returns:
 *     Feedback submission details
 *
 * Raises:
 *     HTTPException: If feedback not found
 * @summary Get Feedback
 */
export const getFeedbackApiV1FeedbackFeedbackIdGet = async (
  feedbackId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<getFeedbackApiV1FeedbackFeedbackIdGetResponse> => {
  return customFetch<getFeedbackApiV1FeedbackFeedbackIdGetResponse>(
    getGetFeedbackApiV1FeedbackFeedbackIdGetUrl(feedbackId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetFeedbackApiV1FeedbackFeedbackIdGetQueryKey = (
  feedbackId: string,
) => {
  return [`/api/v1/feedback/${feedbackId}`] as const;
};

export const getGetFeedbackApiV1FeedbackFeedbackIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
  TError = HTTPValidationError,
>(
  feedbackId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetFeedbackApiV1FeedbackFeedbackIdGetQueryKey(feedbackId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>
  > = ({ signal }) =>
    getFeedbackApiV1FeedbackFeedbackIdGet(feedbackId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: feedbackId !== null && feedbackId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFeedbackApiV1FeedbackFeedbackIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>
>;
export type GetFeedbackApiV1FeedbackFeedbackIdGetQueryError =
  HTTPValidationError;

export function useGetFeedbackApiV1FeedbackFeedbackIdGet<
  TData = Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
  TError = HTTPValidationError,
>(
  feedbackId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedbackApiV1FeedbackFeedbackIdGet<
  TData = Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
  TError = HTTPValidationError,
>(
  feedbackId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeedbackApiV1FeedbackFeedbackIdGet<
  TData = Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
  TError = HTTPValidationError,
>(
  feedbackId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Feedback
 */

export function useGetFeedbackApiV1FeedbackFeedbackIdGet<
  TData = Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
  TError = HTTPValidationError,
>(
  feedbackId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFeedbackApiV1FeedbackFeedbackIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFeedbackApiV1FeedbackFeedbackIdGetQueryOptions(
    feedbackId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
