/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ConnectivityResponse, HealthResponse } from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type liveHealthLiveGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type liveHealthLiveGetResponseSuccess = liveHealthLiveGetResponse200 & {
  headers: Headers;
};
export type liveHealthLiveGetResponse = liveHealthLiveGetResponseSuccess;

export const getLiveHealthLiveGetUrl = () => {
  return `/health/live`;
};

/**
 * @summary Live
 */
export const liveHealthLiveGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<liveHealthLiveGetResponse> => {
  return customFetch<liveHealthLiveGetResponse>(getLiveHealthLiveGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getLiveHealthLiveGetQueryKey = () => {
  return [`/health/live`] as const;
};

export const getLiveHealthLiveGetQueryOptions = <
  TData = Awaited<ReturnType<typeof liveHealthLiveGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof liveHealthLiveGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLiveHealthLiveGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof liveHealthLiveGet>>
  > = ({ signal }) => liveHealthLiveGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof liveHealthLiveGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LiveHealthLiveGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof liveHealthLiveGet>>
>;
export type LiveHealthLiveGetQueryError = unknown;

export function useLiveHealthLiveGet<
  TData = Awaited<ReturnType<typeof liveHealthLiveGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof liveHealthLiveGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveHealthLiveGet>>,
          TError,
          Awaited<ReturnType<typeof liveHealthLiveGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLiveHealthLiveGet<
  TData = Awaited<ReturnType<typeof liveHealthLiveGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof liveHealthLiveGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof liveHealthLiveGet>>,
          TError,
          Awaited<ReturnType<typeof liveHealthLiveGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLiveHealthLiveGet<
  TData = Awaited<ReturnType<typeof liveHealthLiveGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof liveHealthLiveGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Live
 */

export function useLiveHealthLiveGet<
  TData = Awaited<ReturnType<typeof liveHealthLiveGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof liveHealthLiveGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLiveHealthLiveGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type readyHealthReadyGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type readyHealthReadyGetResponseSuccess =
  readyHealthReadyGetResponse200 & {
    headers: Headers;
  };
export type readyHealthReadyGetResponse = readyHealthReadyGetResponseSuccess;

export const getReadyHealthReadyGetUrl = () => {
  return `/health/ready`;
};

/**
 * @summary Ready
 */
export const readyHealthReadyGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<readyHealthReadyGetResponse> => {
  return customFetch<readyHealthReadyGetResponse>(getReadyHealthReadyGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getReadyHealthReadyGetQueryKey = () => {
  return [`/health/ready`] as const;
};

export const getReadyHealthReadyGetQueryOptions = <
  TData = Awaited<ReturnType<typeof readyHealthReadyGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof readyHealthReadyGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReadyHealthReadyGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof readyHealthReadyGet>>
  > = ({ signal }) => readyHealthReadyGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof readyHealthReadyGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReadyHealthReadyGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof readyHealthReadyGet>>
>;
export type ReadyHealthReadyGetQueryError = unknown;

export function useReadyHealthReadyGet<
  TData = Awaited<ReturnType<typeof readyHealthReadyGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof readyHealthReadyGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyHealthReadyGet>>,
          TError,
          Awaited<ReturnType<typeof readyHealthReadyGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReadyHealthReadyGet<
  TData = Awaited<ReturnType<typeof readyHealthReadyGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof readyHealthReadyGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readyHealthReadyGet>>,
          TError,
          Awaited<ReturnType<typeof readyHealthReadyGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useReadyHealthReadyGet<
  TData = Awaited<ReturnType<typeof readyHealthReadyGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof readyHealthReadyGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Ready
 */

export function useReadyHealthReadyGet<
  TData = Awaited<ReturnType<typeof readyHealthReadyGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof readyHealthReadyGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getReadyHealthReadyGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getConnectivityStatusHealthConnectivityGetResponse200 = {
  data: ConnectivityResponse;
  status: 200;
};

export type getConnectivityStatusHealthConnectivityGetResponseSuccess =
  getConnectivityStatusHealthConnectivityGetResponse200 & {
    headers: Headers;
  };
export type getConnectivityStatusHealthConnectivityGetResponse =
  getConnectivityStatusHealthConnectivityGetResponseSuccess;

export const getGetConnectivityStatusHealthConnectivityGetUrl = () => {
  return `/health/connectivity`;
};

/**
 * Check connectivity between frontend and backend.
 * @summary Get Connectivity Status
 */
export const getConnectivityStatusHealthConnectivityGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getConnectivityStatusHealthConnectivityGetResponse> => {
  return customFetch<getConnectivityStatusHealthConnectivityGetResponse>(
    getGetConnectivityStatusHealthConnectivityGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetConnectivityStatusHealthConnectivityGetQueryKey = () => {
  return [`/health/connectivity`] as const;
};

export const getGetConnectivityStatusHealthConnectivityGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetConnectivityStatusHealthConnectivityGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>
  > = ({ signal }) =>
    getConnectivityStatusHealthConnectivityGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConnectivityStatusHealthConnectivityGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>
>;
export type GetConnectivityStatusHealthConnectivityGetQueryError = unknown;

export function useGetConnectivityStatusHealthConnectivityGet<
  TData = Awaited<
    ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
  >,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
          >,
          TError,
          Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConnectivityStatusHealthConnectivityGet<
  TData = Awaited<
    ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
          >,
          TError,
          Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConnectivityStatusHealthConnectivityGet<
  TData = Awaited<
    ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Connectivity Status
 */

export function useGetConnectivityStatusHealthConnectivityGet<
  TData = Awaited<
    ReturnType<typeof getConnectivityStatusHealthConnectivityGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConnectivityStatusHealthConnectivityGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetConnectivityStatusHealthConnectivityGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
