/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DailyStatisticsResponse,
  GetDailyStatisticsApiV1StatisticsDailyGetParams,
  GetMacroStatisticsApiV1StatisticsMacrosGetParams,
  HTTPValidationError,
  MacroStatisticsResponse
} from '../../model';

import { customFetch } from '../../client';




/**
 * Get daily nutrition statistics for a date range.

Returns aggregated nutrition data grouped by day with meal counts,
calorie totals, macronutrient breakdowns, and goal achievement metrics.
Data updates in real-time as meals are logged.

Args:
    request: FastAPI request object (for auth)
    start_date: Start date (inclusive)
    end_date: End date (exclusive)

Returns:
    Daily statistics response with data points and summary

Raises:
    HTTPException: If query fails or date range invalid
 * @summary Get Daily Statistics
 */
export type getDailyStatisticsApiV1StatisticsDailyGetResponse200 = {
  data: DailyStatisticsResponse
  status: 200
}

export type getDailyStatisticsApiV1StatisticsDailyGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDailyStatisticsApiV1StatisticsDailyGetResponseSuccess = (getDailyStatisticsApiV1StatisticsDailyGetResponse200) & {
  headers: Headers;
};
export type getDailyStatisticsApiV1StatisticsDailyGetResponseError = (getDailyStatisticsApiV1StatisticsDailyGetResponse422) & {
  headers: Headers;
};

export type getDailyStatisticsApiV1StatisticsDailyGetResponse = (getDailyStatisticsApiV1StatisticsDailyGetResponseSuccess | getDailyStatisticsApiV1StatisticsDailyGetResponseError)

export const getGetDailyStatisticsApiV1StatisticsDailyGetUrl = (params: GetDailyStatisticsApiV1StatisticsDailyGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/statistics/daily?${stringifiedParams}` : `/api/v1/statistics/daily`
}

export const getDailyStatisticsApiV1StatisticsDailyGet = async (params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options?: RequestInit): Promise<getDailyStatisticsApiV1StatisticsDailyGetResponse> => {

  return customFetch<getDailyStatisticsApiV1StatisticsDailyGetResponse>(getGetDailyStatisticsApiV1StatisticsDailyGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDailyStatisticsApiV1StatisticsDailyGetQueryKey = (params?: GetDailyStatisticsApiV1StatisticsDailyGetParams,) => {
    return [
    `/api/v1/statistics/daily`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDailyStatisticsApiV1StatisticsDailyGetQueryOptions = <TData = Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError = HTTPValidationError>(params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDailyStatisticsApiV1StatisticsDailyGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>> = ({ signal }) => getDailyStatisticsApiV1StatisticsDailyGet(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetDailyStatisticsApiV1StatisticsDailyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>>
export type GetDailyStatisticsApiV1StatisticsDailyGetQueryError = HTTPValidationError


export function useGetDailyStatisticsApiV1StatisticsDailyGet<TData = Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError = HTTPValidationError>(
 params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>,
          TError,
          Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDailyStatisticsApiV1StatisticsDailyGet<TData = Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError = HTTPValidationError>(
 params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>,
          TError,
          Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDailyStatisticsApiV1StatisticsDailyGet<TData = Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError = HTTPValidationError>(
 params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Daily Statistics
 */

export function useGetDailyStatisticsApiV1StatisticsDailyGet<TData = Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError = HTTPValidationError>(
 params: GetDailyStatisticsApiV1StatisticsDailyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyStatisticsApiV1StatisticsDailyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDailyStatisticsApiV1StatisticsDailyGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get macronutrient breakdown for a date range.

Returns aggregated macronutrient distribution showing percentage
and gram totals for protein, fat, and carbohydrates.

Args:
    request: FastAPI request object (for auth)
    start_date: Start date (inclusive)
    end_date: End date (exclusive)

Returns:
    Macronutrient breakdown response

Raises:
    HTTPException: If query fails or date range invalid
 * @summary Get Macro Statistics
 */
export type getMacroStatisticsApiV1StatisticsMacrosGetResponse200 = {
  data: MacroStatisticsResponse
  status: 200
}

export type getMacroStatisticsApiV1StatisticsMacrosGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMacroStatisticsApiV1StatisticsMacrosGetResponseSuccess = (getMacroStatisticsApiV1StatisticsMacrosGetResponse200) & {
  headers: Headers;
};
export type getMacroStatisticsApiV1StatisticsMacrosGetResponseError = (getMacroStatisticsApiV1StatisticsMacrosGetResponse422) & {
  headers: Headers;
};

export type getMacroStatisticsApiV1StatisticsMacrosGetResponse = (getMacroStatisticsApiV1StatisticsMacrosGetResponseSuccess | getMacroStatisticsApiV1StatisticsMacrosGetResponseError)

export const getGetMacroStatisticsApiV1StatisticsMacrosGetUrl = (params: GetMacroStatisticsApiV1StatisticsMacrosGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/statistics/macros?${stringifiedParams}` : `/api/v1/statistics/macros`
}

export const getMacroStatisticsApiV1StatisticsMacrosGet = async (params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options?: RequestInit): Promise<getMacroStatisticsApiV1StatisticsMacrosGetResponse> => {

  return customFetch<getMacroStatisticsApiV1StatisticsMacrosGetResponse>(getGetMacroStatisticsApiV1StatisticsMacrosGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMacroStatisticsApiV1StatisticsMacrosGetQueryKey = (params?: GetMacroStatisticsApiV1StatisticsMacrosGetParams,) => {
    return [
    `/api/v1/statistics/macros`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMacroStatisticsApiV1StatisticsMacrosGetQueryOptions = <TData = Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError = HTTPValidationError>(params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMacroStatisticsApiV1StatisticsMacrosGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>> = ({ signal }) => getMacroStatisticsApiV1StatisticsMacrosGet(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMacroStatisticsApiV1StatisticsMacrosGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>>
export type GetMacroStatisticsApiV1StatisticsMacrosGetQueryError = HTTPValidationError


export function useGetMacroStatisticsApiV1StatisticsMacrosGet<TData = Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError = HTTPValidationError>(
 params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>,
          TError,
          Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMacroStatisticsApiV1StatisticsMacrosGet<TData = Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError = HTTPValidationError>(
 params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>,
          TError,
          Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMacroStatisticsApiV1StatisticsMacrosGet<TData = Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError = HTTPValidationError>(
 params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Macro Statistics
 */

export function useGetMacroStatisticsApiV1StatisticsMacrosGet<TData = Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError = HTTPValidationError>(
 params: GetMacroStatisticsApiV1StatisticsMacrosGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMacroStatisticsApiV1StatisticsMacrosGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMacroStatisticsApiV1StatisticsMacrosGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}
