/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DevelopmentEnvironment,
  GetDbStatusApiV1DevDbStatusGet200,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDevelopmentEnvironmentApiV1DevEnvironmentGetResponse200 = {
  data: DevelopmentEnvironment;
  status: 200;
};

export type getDevelopmentEnvironmentApiV1DevEnvironmentGetResponseSuccess =
  getDevelopmentEnvironmentApiV1DevEnvironmentGetResponse200 & {
    headers: Headers;
  };
export type getDevelopmentEnvironmentApiV1DevEnvironmentGetResponse =
  getDevelopmentEnvironmentApiV1DevEnvironmentGetResponseSuccess;

export const getGetDevelopmentEnvironmentApiV1DevEnvironmentGetUrl = () => {
  return `/api/v1/dev/environment`;
};

/**
 * Get current development environment configuration.
 * @summary Get Development Environment
 */
export const getDevelopmentEnvironmentApiV1DevEnvironmentGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getDevelopmentEnvironmentApiV1DevEnvironmentGetResponse> => {
  return customFetch<getDevelopmentEnvironmentApiV1DevEnvironmentGetResponse>(
    getGetDevelopmentEnvironmentApiV1DevEnvironmentGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryKey =
  () => {
    return [`/api/v1/dev/environment`] as const;
  };

export const getGetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
      >,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>>
  > = ({ signal }) =>
    getDevelopmentEnvironmentApiV1DevEnvironmentGet({
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>>
  >;
export type GetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryError = unknown;

export function useGetDevelopmentEnvironmentApiV1DevEnvironmentGet<
  TData = Awaited<
    ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
  >,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevelopmentEnvironmentApiV1DevEnvironmentGet<
  TData = Awaited<
    ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevelopmentEnvironmentApiV1DevEnvironmentGet<
  TData = Awaited<
    ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Development Environment
 */

export function useGetDevelopmentEnvironmentApiV1DevEnvironmentGet<
  TData = Awaited<
    ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getDevelopmentEnvironmentApiV1DevEnvironmentGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetDevelopmentEnvironmentApiV1DevEnvironmentGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getDbStatusApiV1DevDbStatusGetResponse200 = {
  data: GetDbStatusApiV1DevDbStatusGet200;
  status: 200;
};

export type getDbStatusApiV1DevDbStatusGetResponseSuccess =
  getDbStatusApiV1DevDbStatusGetResponse200 & {
    headers: Headers;
  };
export type getDbStatusApiV1DevDbStatusGetResponse =
  getDbStatusApiV1DevDbStatusGetResponseSuccess;

export const getGetDbStatusApiV1DevDbStatusGetUrl = () => {
  return `/api/v1/dev/db/status`;
};

/**
 * Get database connection pool status.
 * @summary Get Db Status
 */
export const getDbStatusApiV1DevDbStatusGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getDbStatusApiV1DevDbStatusGetResponse> => {
  return customFetch<getDbStatusApiV1DevDbStatusGetResponse>(
    getGetDbStatusApiV1DevDbStatusGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetDbStatusApiV1DevDbStatusGetQueryKey = () => {
  return [`/api/v1/dev/db/status`] as const;
};

export const getGetDbStatusApiV1DevDbStatusGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDbStatusApiV1DevDbStatusGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>
  > = ({ signal }) =>
    getDbStatusApiV1DevDbStatusGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDbStatusApiV1DevDbStatusGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>
>;
export type GetDbStatusApiV1DevDbStatusGetQueryError = unknown;

export function useGetDbStatusApiV1DevDbStatusGet<
  TData = Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDbStatusApiV1DevDbStatusGet<
  TData = Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDbStatusApiV1DevDbStatusGet<
  TData = Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Db Status
 */

export function useGetDbStatusApiV1DevDbStatusGet<
  TData = Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDbStatusApiV1DevDbStatusGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDbStatusApiV1DevDbStatusGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
