/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreateLogEntryApiV1LogsPost200,
  HTTPValidationError,
  LogEntryCreate,
} from "../../model";

import { customFetch } from "../../client";

/**
 * Accept a frontend log entry and forward it to structlog.
 * @summary Create Log Entry
 */
export type createLogEntryApiV1LogsPostResponse200 = {
  data: CreateLogEntryApiV1LogsPost200;
  status: 200;
};

export type createLogEntryApiV1LogsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createLogEntryApiV1LogsPostResponseSuccess =
  createLogEntryApiV1LogsPostResponse200 & {
    headers: Headers;
  };
export type createLogEntryApiV1LogsPostResponseError =
  createLogEntryApiV1LogsPostResponse422 & {
    headers: Headers;
  };

export type createLogEntryApiV1LogsPostResponse =
  | createLogEntryApiV1LogsPostResponseSuccess
  | createLogEntryApiV1LogsPostResponseError;

export const getCreateLogEntryApiV1LogsPostUrl = () => {
  return `/api/v1/logs`;
};

export const createLogEntryApiV1LogsPost = async (
  logEntryCreate: LogEntryCreate,
  options?: RequestInit,
): Promise<createLogEntryApiV1LogsPostResponse> => {
  return customFetch<createLogEntryApiV1LogsPostResponse>(
    getCreateLogEntryApiV1LogsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(logEntryCreate),
    },
  );
};

export const getCreateLogEntryApiV1LogsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
    TError,
    { data: LogEntryCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
  TError,
  { data: LogEntryCreate },
  TContext
> => {
  const mutationKey = ["createLogEntryApiV1LogsPost"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
    { data: LogEntryCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createLogEntryApiV1LogsPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLogEntryApiV1LogsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>
>;
export type CreateLogEntryApiV1LogsPostMutationBody = LogEntryCreate;
export type CreateLogEntryApiV1LogsPostMutationError = HTTPValidationError;

/**
 * @summary Create Log Entry
 */
export const useCreateLogEntryApiV1LogsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
      TError,
      { data: LogEntryCreate },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
  TError,
  { data: LogEntryCreate },
  TContext
> => {
  return useMutation(
    getCreateLogEntryApiV1LogsPostMutationOptions(options),
    queryClient,
  );
};
