/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreateLogEntryApiV1LogsPost200,
  HTTPValidationError,
  LogEntryCreate,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type createLogEntryApiV1LogsPostResponse200 = {
  data: CreateLogEntryApiV1LogsPost200;
  status: 200;
};

export type createLogEntryApiV1LogsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createLogEntryApiV1LogsPostResponseSuccess =
  createLogEntryApiV1LogsPostResponse200 & {
    headers: Headers;
  };
export type createLogEntryApiV1LogsPostResponseError =
  createLogEntryApiV1LogsPostResponse422 & {
    headers: Headers;
  };

export type createLogEntryApiV1LogsPostResponse =
  | createLogEntryApiV1LogsPostResponseSuccess
  | createLogEntryApiV1LogsPostResponseError;

export const getCreateLogEntryApiV1LogsPostUrl = () => {
  return `/api/v1/logs`;
};

/**
 * Accept a frontend log entry and forward it to structlog.
 * @summary Create Log Entry
 */
export const createLogEntryApiV1LogsPost = async (
  logEntryCreate: LogEntryCreate,
  options?: Parameters<typeof customFetch>[1],
): Promise<createLogEntryApiV1LogsPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<createLogEntryApiV1LogsPostResponse>(
    getCreateLogEntryApiV1LogsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(logEntryCreate),
    },
  );
};

export const getCreateLogEntryApiV1LogsPostMutationKey = () =>
  ["createLogEntryApiV1LogsPost"] as const;

export const getCreateLogEntryApiV1LogsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
    TError,
    CreateLogEntryApiV1LogsPostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
  TError,
  CreateLogEntryApiV1LogsPostMutationVariables,
  TContext
> => {
  const mutationKey = getCreateLogEntryApiV1LogsPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
    CreateLogEntryApiV1LogsPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createLogEntryApiV1LogsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLogEntryApiV1LogsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>
>;
export type CreateLogEntryApiV1LogsPostMutationBody = LogEntryCreate;
export type CreateLogEntryApiV1LogsPostMutationError = HTTPValidationError;
export type CreateLogEntryApiV1LogsPostMutationVariables = {
  data: LogEntryCreate;
};

/**
 * @summary Create Log Entry
 */
export const useCreateLogEntryApiV1LogsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
      TError,
      CreateLogEntryApiV1LogsPostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLogEntryApiV1LogsPost>>,
  TError,
  CreateLogEntryApiV1LogsPostMutationVariables,
  TContext
> => {
  return useMutation(
    getCreateLogEntryApiV1LogsPostMutationOptions(options),
    queryClient,
  );
};
