/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectionStatus } from "./connectionStatus";
import type { ConnectivityResponseServices } from "./connectivityResponseServices";

export interface ConnectivityResponse {
  status: ConnectionStatus;
  services: ConnectivityResponseServices;
  response_time_ms: number;
  correlation_id: string;
  timestamp: string;
}
