/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type ConnectionStatus =
  (typeof ConnectionStatus)[keyof typeof ConnectionStatus];

export const ConnectionStatus = {
  connected: "connected",
  disconnected: "disconnected",
  error: "error",
} as const;
