/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface DailyDataPoint {
  date: string;
  /** @minimum 0 */
  total_calories: number;
  /** @minimum 0 */
  total_protein: number;
  /** @minimum 0 */
  total_fat: number;
  /** @minimum 0 */
  total_carbs: number;
  /** @minimum 0 */
  meal_count: number;
  goal_calories?: number | null;
  goal_achievement?: number | null;
}
