/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { MacrosTotals } from "./macrosTotals";

export interface DailySummary {
  user_id: string;
  date: string;
  /** @minimum 0 */
  kcal_total: number;
  macros_totals: MacrosTotals;
}
