/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyDataPoint } from "./dailyDataPoint";
import type { StatisticsPeriod } from "./statisticsPeriod";
import type { StatisticsSummary } from "./statisticsSummary";

export interface DailyStatisticsResponse {
  data: DailyDataPoint[];
  period: StatisticsPeriod;
  summary: StatisticsSummary;
}
