/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface DevelopmentEnvironment {
  id: string;
  name: string;
  frontend_port: number;
  backend_port: number;
  database_url: string;
  database_password: string;
  redis_url: string;
  storage_endpoint: string;
  cors_origins: string[];
  log_level: string;
  hot_reload: boolean;
  created_at: string;
  updated_at: string;
}
