/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type Environment = (typeof Environment)[keyof typeof Environment];

export const Environment = {
  development: "development",
  production: "production",
} as const;
