/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface EstimateItem {
  label: string;
  kcal: number;
  confidence: number;
}
