/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { Status } from "./status";

export interface EstimateQueuedResponse {
  estimate_id: string;
  status: Status;
}
