/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { EstimateItem } from './estimateItem';
import type { Status } from './status';

export interface EstimateResponse {
  /** Estimate ID */
  id: string;
  photo_id: string;
  kcal_mean: number;
  kcal_min: number;
  kcal_max: number;
  confidence: number;
  breakdown: EstimateItem[];
  status?: Status | null;
}
