/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackMessageType } from "./feedbackMessageType";
import type { FeedbackStatus } from "./feedbackStatus";
import type { FeedbackSubmissionUserContext } from "./feedbackSubmissionUserContext";

export interface FeedbackSubmission {
  id: string;
  user_id: string;
  message_type: FeedbackMessageType;
  message_content: string;
  user_context?: FeedbackSubmissionUserContext;
  status: FeedbackStatus;
  admin_notes?: string | null;
  created_at: string;
  updated_at: string;
}
