/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type FeedbackStatus = typeof FeedbackStatus[keyof typeof FeedbackStatus];


export const FeedbackStatus = {
  new: 'new',
  reviewed: 'reviewed',
  resolved: 'resolved',
} as const;
