/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackStatus } from "./feedbackStatus";

export interface FeedbackSubmissionResponse {
  id: string;
  status: FeedbackStatus;
  created_at: string;
  message: string;
}
