/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type FeedbackMessageType = typeof FeedbackMessageType[keyof typeof FeedbackMessageType];


export const FeedbackMessageType = {
  feedback: 'feedback',
  bug: 'bug',
  question: 'question',
  support: 'support',
} as const;
