/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackMessageType } from "./feedbackMessageType";
import type { FeedbackSubmissionRequestUserContext } from "./feedbackSubmissionRequestUserContext";

export interface FeedbackSubmissionRequest {
  message_type: FeedbackMessageType;
  /**
   * @minLength 1
   * @maxLength 5000
   */
  message_content: string;
  user_context?: FeedbackSubmissionRequestUserContext;
}
