/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetDailyStatisticsApiV1StatisticsDailyGetParams = {
  /**
   * Start date (inclusive) in YYYY-MM-DD format
   */
  start_date: string;
  /**
   * End date (exclusive) in YYYY-MM-DD format
   */
  end_date: string;
};
