/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetInlineSummaryApiV1AnalyticsInlineSummaryGet200 = {
  [key: string]: unknown;
};
