/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetInlineSummaryApiV1AnalyticsInlineSummaryGetParams = {
  range_start?: string | null;
  range_end?: string | null;
  chat_type?: string | null;
};
