/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetMonthlySummaryApiV1MonthlySummaryGetParams = {
/**
 * Year
 */
year: number;
/**
 * Month (1-12)
 */
month: number;
};
