/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetMealsCalendarApiV1MealsCalendarGetParams = {
/**
 * Start date (YYYY-MM-DD)
 */
start_date: string;
/**
 * End date (YYYY-MM-DD)
 */
end_date: string;
};
