/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type GetWeeklySummaryApiV1WeeklySummaryGetParams = {
  /**
   * Start date in YYYY-MM-DD format
   */
  start_date: string;
};
