/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface GoalResponse {
  id: string;
  user_id: string;
  daily_kcal_target: number;
  created_at?: string | null;
  updated_at?: string | null;
}
