/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type LanguageSource = typeof LanguageSource[keyof typeof LanguageSource];


export const LanguageSource = {
  telegram: 'telegram',
  browser: 'browser',
  manual: 'manual',
} as const;
