/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { LanguageSource } from "./languageSource";

export interface LanguageDetectionResponse {
  language: string;
  language_source: LanguageSource;
  telegram_language_code?: string | null;
  browser_language?: string | null;
  detected_at: string;
  supported_languages: string[];
}
