/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { LogEntryCreateContext } from './logEntryCreateContext';
import type { LogLevel } from './logLevel';

export interface LogEntryCreate {
  level: LogLevel;
  message: string;
  correlation_id?: string | null;
  module?: string | null;
  function?: string | null;
  context?: LogEntryCreateContext;
  inline_trigger?: string | null;
  inline_stage?: string | null;
}
