/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface MacrosTotals {
  /** @minimum 0 */
  protein_g: number;
  /** @minimum 0 */
  fat_g: number;
  /** @minimum 0 */
  carbs_g: number;
}
