/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { StatisticsPeriod } from "./statisticsPeriod";

export interface MacroStatisticsResponse {
  /**
   * @minimum 0
   * @maximum 100
   */
  protein_percent: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  fat_percent: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  carbs_percent: number;
  /** @minimum 0 */
  protein_grams: number;
  /** @minimum 0 */
  fat_grams: number;
  /** @minimum 0 */
  carbs_grams: number;
  /** @minimum 0 */
  total_calories: number;
  period: StatisticsPeriod;
}
