/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface Macronutrients {
  /** @minimum 0 */
  protein: number;
  /** @minimum 0 */
  carbs: number;
  /** @minimum 0 */
  fats: number;
}
