/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { MealWithPhotos } from "./mealWithPhotos";

export interface MealsListResponse {
  meals: MealWithPhotos[];
  /** @minimum 0 */
  total: number;
}
