/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { MealCalendarDay } from "./mealCalendarDay";

export interface MealsCalendarResponse {
  dates: MealCalendarDay[];
}
