/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface MealPhotoInfo {
  id: string;
  /** Presigned URL for thumbnail */
  thumbnailUrl: string;
  /** Presigned URL for full-size image */
  fullUrl: string;
  /**
   * Position in carousel (0-4)
   * @minimum 0
   * @maximum 4
   */
  displayOrder: number;
}
