/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { MealCreateFromEstimateRequestOverrides } from "./mealCreateFromEstimateRequestOverrides";
import type { MealType } from "./mealType";

export interface MealCreateFromEstimateRequest {
  meal_date: string;
  meal_type: MealType;
  estimate_id: string;
  overrides?: MealCreateFromEstimateRequestOverrides;
}
