/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { Macronutrients } from './macronutrients';
import type { MealPhotoInfo } from './mealPhotoInfo';

export interface MealWithPhotos {
  id: string;
  userId: string;
  createdAt: string;
  description?: string | null;
  /** @minimum 0 */
  calories: number;
  macronutrients: Macronutrients;
  photos?: MealPhotoInfo[] | null;
  /** AI confidence (0-1) */
  confidenceScore?: number | null;
}
