/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { Macronutrients } from './macronutrients';
import type { MealType } from './mealType';

export interface MealCreateManualRequest {
  meal_date: string;
  meal_type: MealType;
  kcal_total: number;
  macros?: Macronutrients | null;
}
