/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { PhotoCreateRequest } from './photoCreateRequest';

export interface MultiPhotoCreateRequest {
  /**
   * List of photos to upload (1-5 photos)
   * @minItems 1
   * @maxItems 5
   */
  photos: PhotoCreateRequest[];
}
