/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { PhotoInfo } from "./photoInfo";

export interface MultiPhotoResponse {
  photos: PhotoInfo[];
}
