/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface StatisticsSummary {
  /** @minimum 0 */
  total_meals: number;
  /** @minimum 0 */
  average_daily_calories: number;
  average_goal_achievement?: number | null;
}
