/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export interface StatisticsPeriod {
  start_date: string;
  end_date: string;
  /** @minimum 1 */
  total_days: number;
}
