/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type Theme = (typeof Theme)[keyof typeof Theme];

export const Theme = {
  light: "light",
  dark: "dark",
  auto: "auto",
} as const;
