/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { Theme } from "./theme";
import type { ThemeSource } from "./themeSource";

export interface ThemeDetectionResponse {
  theme: Theme;
  theme_source: ThemeSource;
  telegram_color_scheme?: string | null;
  system_prefers_dark?: boolean | null;
  detected_at: string;
}
