/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */

export type ThemeSource = (typeof ThemeSource)[keyof typeof ThemeSource];

export const ThemeSource = {
  telegram: "telegram",
  system: "system",
  manual: "manual",
} as const;
