/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { DailySummary } from "./dailySummary";
import type { TodayResponseMealsItem } from "./todayResponseMealsItem";

export interface TodayResponse {
  meals: TodayResponseMealsItem[];
  daily_summary: DailySummary;
}
