/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import type { Environment } from './environment';
import type { LanguageSource } from './languageSource';
import type { Theme } from './theme';
import type { ThemeSource } from './themeSource';
import type { UIConfigurationFeatures } from './uIConfigurationFeatures';

export interface UIConfiguration {
  id: string;
  environment: Environment;
  api_base_url: string;
  safe_area_top?: number | null;
  safe_area_bottom?: number | null;
  safe_area_left?: number | null;
  safe_area_right?: number | null;
  theme?: Theme | null;
  theme_source?: ThemeSource | null;
  language?: string | null;
  language_source?: LanguageSource | null;
  features?: UIConfigurationFeatures;
  created_at: string;
  updated_at: string;
}
