/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetMealsApiV1MealsGetParams,
  GetMealsCalendarApiV1MealsCalendarGetParams,
  HTTPValidationError,
  MealCreateFromEstimateRequest,
  MealCreateManualRequest,
  MealCreateResponse,
  MealUpdate,
  MealWithPhotos,
  MealsCalendarResponse,
  MealsListResponse,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createMealApiV1MealsPostResponse200 = {
  data: MealCreateResponse;
  status: 200;
};

export type createMealApiV1MealsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createMealApiV1MealsPostResponseSuccess =
  createMealApiV1MealsPostResponse200 & {
    headers: Headers;
  };
export type createMealApiV1MealsPostResponseError =
  createMealApiV1MealsPostResponse422 & {
    headers: Headers;
  };

export type createMealApiV1MealsPostResponse =
  | createMealApiV1MealsPostResponseSuccess
  | createMealApiV1MealsPostResponseError;

export const getCreateMealApiV1MealsPostUrl = () => {
  return `/api/v1/meals`;
};

/**
 * @summary Create Meal
 */
export const createMealApiV1MealsPost = async (
  mealCreateManualRequestMealCreateFromEstimateRequest:
    | MealCreateManualRequest
    | MealCreateFromEstimateRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<createMealApiV1MealsPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<createMealApiV1MealsPostResponse>(
    getCreateMealApiV1MealsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(
        mealCreateManualRequestMealCreateFromEstimateRequest,
      ),
    },
  );
};

export const getCreateMealApiV1MealsPostMutationKey = () =>
  ["createMealApiV1MealsPost"] as const;

export const getCreateMealApiV1MealsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMealApiV1MealsPost>>,
    TError,
    CreateMealApiV1MealsPostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMealApiV1MealsPost>>,
  TError,
  CreateMealApiV1MealsPostMutationVariables,
  TContext
> => {
  const mutationKey = getCreateMealApiV1MealsPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMealApiV1MealsPost>>,
    CreateMealApiV1MealsPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createMealApiV1MealsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMealApiV1MealsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMealApiV1MealsPost>>
>;
export type CreateMealApiV1MealsPostMutationBody =
  | MealCreateManualRequest
  | MealCreateFromEstimateRequest;
export type CreateMealApiV1MealsPostMutationError = HTTPValidationError;
export type CreateMealApiV1MealsPostMutationVariables = {
  data: MealCreateManualRequest | MealCreateFromEstimateRequest;
};

/**
 * @summary Create Meal
 */
export const useCreateMealApiV1MealsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createMealApiV1MealsPost>>,
      TError,
      CreateMealApiV1MealsPostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createMealApiV1MealsPost>>,
  TError,
  CreateMealApiV1MealsPostMutationVariables,
  TContext
> => {
  return useMutation(
    getCreateMealApiV1MealsPostMutationOptions(options),
    queryClient,
  );
};
export type getMealsApiV1MealsGetResponse200 = {
  data: MealsListResponse;
  status: 200;
};

export type getMealsApiV1MealsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMealsApiV1MealsGetResponseSuccess =
  getMealsApiV1MealsGetResponse200 & {
    headers: Headers;
  };
export type getMealsApiV1MealsGetResponseError =
  getMealsApiV1MealsGetResponse422 & {
    headers: Headers;
  };

export type getMealsApiV1MealsGetResponse =
  | getMealsApiV1MealsGetResponseSuccess
  | getMealsApiV1MealsGetResponseError;

export const getGetMealsApiV1MealsGetUrl = (
  params?: GetMealsApiV1MealsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/meals?${stringifiedParams}`
    : `/api/v1/meals`;
};

/**
 * Get meals with photos and macronutrients.
 *
 * Feature: 003-update-logic-for (Multi-photo support)
 * Supports:
 * - Single date query: ?date=2025-09-30
 * - Date range query: ?start_date=2025-09-23&end_date=2025-09-30
 * - Default: today's meals
 * @summary Get Meals
 */
export const getMealsApiV1MealsGet = async (
  params?: GetMealsApiV1MealsGetParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<getMealsApiV1MealsGetResponse> => {
  return customFetch<getMealsApiV1MealsGetResponse>(
    getGetMealsApiV1MealsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMealsApiV1MealsGetQueryKey = (
  params?: GetMealsApiV1MealsGetParams,
) => {
  return [`/api/v1/meals`, ...(params ? [params] : [])] as const;
};

export const getGetMealsApiV1MealsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetMealsApiV1MealsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMealsApiV1MealsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMealsApiV1MealsGet>>
  > = ({ signal }) =>
    getMealsApiV1MealsGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMealsApiV1MealsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMealsApiV1MealsGet>>
>;
export type GetMealsApiV1MealsGetQueryError = HTTPValidationError;

export function useGetMealsApiV1MealsGet<
  TData = Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
  TError = HTTPValidationError,
>(
  params: undefined | GetMealsApiV1MealsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
          TError,
          Awaited<ReturnType<typeof getMealsApiV1MealsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealsApiV1MealsGet<
  TData = Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetMealsApiV1MealsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
          TError,
          Awaited<ReturnType<typeof getMealsApiV1MealsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealsApiV1MealsGet<
  TData = Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetMealsApiV1MealsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Meals
 */

export function useGetMealsApiV1MealsGet<
  TData = Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetMealsApiV1MealsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsApiV1MealsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMealsApiV1MealsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getMealsCalendarApiV1MealsCalendarGetResponse200 = {
  data: MealsCalendarResponse;
  status: 200;
};

export type getMealsCalendarApiV1MealsCalendarGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMealsCalendarApiV1MealsCalendarGetResponseSuccess =
  getMealsCalendarApiV1MealsCalendarGetResponse200 & {
    headers: Headers;
  };
export type getMealsCalendarApiV1MealsCalendarGetResponseError =
  getMealsCalendarApiV1MealsCalendarGetResponse422 & {
    headers: Headers;
  };

export type getMealsCalendarApiV1MealsCalendarGetResponse =
  | getMealsCalendarApiV1MealsCalendarGetResponseSuccess
  | getMealsCalendarApiV1MealsCalendarGetResponseError;

export const getGetMealsCalendarApiV1MealsCalendarGetUrl = (
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/meals/calendar?${stringifiedParams}`
    : `/api/v1/meals/calendar`;
};

/**
 * Get daily meal summaries for calendar view.
 *
 * Feature: 003-update-logic-for (Calendar navigation)
 * Returns aggregated nutrition data by date.
 * @summary Get Meals Calendar
 */
export const getMealsCalendarApiV1MealsCalendarGet = async (
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<getMealsCalendarApiV1MealsCalendarGetResponse> => {
  return customFetch<getMealsCalendarApiV1MealsCalendarGetResponse>(
    getGetMealsCalendarApiV1MealsCalendarGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMealsCalendarApiV1MealsCalendarGetQueryKey = (
  params?: GetMealsCalendarApiV1MealsCalendarGetParams,
) => {
  return [`/api/v1/meals/calendar`, ...(params ? [params] : [])] as const;
};

export const getGetMealsCalendarApiV1MealsCalendarGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
  TError = HTTPValidationError,
>(
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMealsCalendarApiV1MealsCalendarGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>
  > = ({ signal }) =>
    getMealsCalendarApiV1MealsCalendarGet(params, {
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMealsCalendarApiV1MealsCalendarGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>
>;
export type GetMealsCalendarApiV1MealsCalendarGetQueryError =
  HTTPValidationError;

export function useGetMealsCalendarApiV1MealsCalendarGet<
  TData = Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
  TError = HTTPValidationError,
>(
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
          TError,
          Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealsCalendarApiV1MealsCalendarGet<
  TData = Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
  TError = HTTPValidationError,
>(
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
          TError,
          Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealsCalendarApiV1MealsCalendarGet<
  TData = Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
  TError = HTTPValidationError,
>(
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Meals Calendar
 */

export function useGetMealsCalendarApiV1MealsCalendarGet<
  TData = Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
  TError = HTTPValidationError,
>(
  params: GetMealsCalendarApiV1MealsCalendarGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealsCalendarApiV1MealsCalendarGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMealsCalendarApiV1MealsCalendarGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getMealApiV1MealsMealIdGetResponse200 = {
  data: MealWithPhotos;
  status: 200;
};

export type getMealApiV1MealsMealIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMealApiV1MealsMealIdGetResponseSuccess =
  getMealApiV1MealsMealIdGetResponse200 & {
    headers: Headers;
  };
export type getMealApiV1MealsMealIdGetResponseError =
  getMealApiV1MealsMealIdGetResponse422 & {
    headers: Headers;
  };

export type getMealApiV1MealsMealIdGetResponse =
  | getMealApiV1MealsMealIdGetResponseSuccess
  | getMealApiV1MealsMealIdGetResponseError;

export const getGetMealApiV1MealsMealIdGetUrl = (mealId: string) => {
  return `/api/v1/meals/${mealId}`;
};

/**
 * Get a specific meal with photos and macronutrients.
 *
 * Feature: 003-update-logic-for (Multi-photo support)
 * @summary Get Meal
 */
export const getMealApiV1MealsMealIdGet = async (
  mealId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<getMealApiV1MealsMealIdGetResponse> => {
  return customFetch<getMealApiV1MealsMealIdGetResponse>(
    getGetMealApiV1MealsMealIdGetUrl(mealId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMealApiV1MealsMealIdGetQueryKey = (mealId: string) => {
  return [`/api/v1/meals/${mealId}`] as const;
};

export const getGetMealApiV1MealsMealIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
  TError = HTTPValidationError,
>(
  mealId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMealApiV1MealsMealIdGetQueryKey(mealId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>
  > = ({ signal }) =>
    getMealApiV1MealsMealIdGet(mealId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: mealId !== null && mealId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMealApiV1MealsMealIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>
>;
export type GetMealApiV1MealsMealIdGetQueryError = HTTPValidationError;

export function useGetMealApiV1MealsMealIdGet<
  TData = Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
  TError = HTTPValidationError,
>(
  mealId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealApiV1MealsMealIdGet<
  TData = Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
  TError = HTTPValidationError,
>(
  mealId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMealApiV1MealsMealIdGet<
  TData = Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
  TError = HTTPValidationError,
>(
  mealId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Meal
 */

export function useGetMealApiV1MealsMealIdGet<
  TData = Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
  TError = HTTPValidationError,
>(
  mealId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMealApiV1MealsMealIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMealApiV1MealsMealIdGetQueryOptions(
    mealId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateMealApiV1MealsMealIdPatchResponse200 = {
  data: MealWithPhotos;
  status: 200;
};

export type updateMealApiV1MealsMealIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateMealApiV1MealsMealIdPatchResponseSuccess =
  updateMealApiV1MealsMealIdPatchResponse200 & {
    headers: Headers;
  };
export type updateMealApiV1MealsMealIdPatchResponseError =
  updateMealApiV1MealsMealIdPatchResponse422 & {
    headers: Headers;
  };

export type updateMealApiV1MealsMealIdPatchResponse =
  | updateMealApiV1MealsMealIdPatchResponseSuccess
  | updateMealApiV1MealsMealIdPatchResponseError;

export const getUpdateMealApiV1MealsMealIdPatchUrl = (mealId: string) => {
  return `/api/v1/meals/${mealId}`;
};

/**
 * Update meal description or macronutrients.
 *
 * Feature: 003-update-logic-for (Meal editing)
 * Automatically recalculates calories from macros if updated.
 * @summary Update Meal
 */
export const updateMealApiV1MealsMealIdPatch = async (
  mealId: string,
  mealUpdate: MealUpdate,
  options?: Parameters<typeof customFetch>[1],
): Promise<updateMealApiV1MealsMealIdPatchResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<updateMealApiV1MealsMealIdPatchResponse>(
    getUpdateMealApiV1MealsMealIdPatchUrl(mealId),
    {
      ...options,
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(mealUpdate),
    },
  );
};

export const getUpdateMealApiV1MealsMealIdPatchMutationKey = () =>
  ["updateMealApiV1MealsMealIdPatch"] as const;

export const getUpdateMealApiV1MealsMealIdPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>,
    TError,
    UpdateMealApiV1MealsMealIdPatchMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>,
  TError,
  UpdateMealApiV1MealsMealIdPatchMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateMealApiV1MealsMealIdPatchMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>,
    UpdateMealApiV1MealsMealIdPatchMutationVariables
  > = (props) => {
    const { mealId, data } = props ?? {};

    return updateMealApiV1MealsMealIdPatch(mealId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMealApiV1MealsMealIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>
>;
export type UpdateMealApiV1MealsMealIdPatchMutationBody = MealUpdate;
export type UpdateMealApiV1MealsMealIdPatchMutationError = HTTPValidationError;
export type UpdateMealApiV1MealsMealIdPatchMutationVariables = {
  mealId: string;
  data: MealUpdate;
};

/**
 * @summary Update Meal
 */
export const useUpdateMealApiV1MealsMealIdPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>,
      TError,
      UpdateMealApiV1MealsMealIdPatchMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateMealApiV1MealsMealIdPatch>>,
  TError,
  UpdateMealApiV1MealsMealIdPatchMutationVariables,
  TContext
> => {
  return useMutation(
    getUpdateMealApiV1MealsMealIdPatchMutationOptions(options),
    queryClient,
  );
};
export type deleteMealApiV1MealsMealIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteMealApiV1MealsMealIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteMealApiV1MealsMealIdDeleteResponseSuccess =
  deleteMealApiV1MealsMealIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteMealApiV1MealsMealIdDeleteResponseError =
  deleteMealApiV1MealsMealIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteMealApiV1MealsMealIdDeleteResponse =
  | deleteMealApiV1MealsMealIdDeleteResponseSuccess
  | deleteMealApiV1MealsMealIdDeleteResponseError;

export const getDeleteMealApiV1MealsMealIdDeleteUrl = (mealId: string) => {
  return `/api/v1/meals/${mealId}`;
};

/**
 * Delete a meal and update daily summary.
 *
 * Feature: 003-update-logic-for (Meal management)
 * Cascades to photos and recalculates daily stats.
 * @summary Delete Meal
 */
export const deleteMealApiV1MealsMealIdDelete = async (
  mealId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<deleteMealApiV1MealsMealIdDeleteResponse> => {
  return customFetch<deleteMealApiV1MealsMealIdDeleteResponse>(
    getDeleteMealApiV1MealsMealIdDeleteUrl(mealId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteMealApiV1MealsMealIdDeleteMutationKey = () =>
  ["deleteMealApiV1MealsMealIdDelete"] as const;

export const getDeleteMealApiV1MealsMealIdDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>,
    TError,
    DeleteMealApiV1MealsMealIdDeleteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>,
  TError,
  DeleteMealApiV1MealsMealIdDeleteMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteMealApiV1MealsMealIdDeleteMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>,
    DeleteMealApiV1MealsMealIdDeleteMutationVariables
  > = (props) => {
    const { mealId } = props ?? {};

    return deleteMealApiV1MealsMealIdDelete(mealId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMealApiV1MealsMealIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>
>;

export type DeleteMealApiV1MealsMealIdDeleteMutationError = HTTPValidationError;
export type DeleteMealApiV1MealsMealIdDeleteMutationVariables = {
  mealId: string;
};

/**
 * @summary Delete Meal
 */
export const useDeleteMealApiV1MealsMealIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>,
      TError,
      DeleteMealApiV1MealsMealIdDeleteMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMealApiV1MealsMealIdDelete>>,
  TError,
  DeleteMealApiV1MealsMealIdDeleteMutationVariables,
  TContext
> => {
  return useMutation(
    getDeleteMealApiV1MealsMealIdDeleteMutationOptions(options),
    queryClient,
  );
};
