/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  LanguageDetectionResponse,
  ThemeDetectionResponse,
  UIConfiguration,
  UIConfigurationUpdate,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getUiConfigurationApiV1ConfigUiGetResponse200 = {
  data: UIConfiguration;
  status: 200;
};

export type getUiConfigurationApiV1ConfigUiGetResponseSuccess =
  getUiConfigurationApiV1ConfigUiGetResponse200 & {
    headers: Headers;
  };
export type getUiConfigurationApiV1ConfigUiGetResponse =
  getUiConfigurationApiV1ConfigUiGetResponseSuccess;

export const getGetUiConfigurationApiV1ConfigUiGetUrl = () => {
  return `/api/v1/config/ui`;
};

/**
 * Get current UI configuration for the user.
 * @summary Get Ui Configuration
 */
export const getUiConfigurationApiV1ConfigUiGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<getUiConfigurationApiV1ConfigUiGetResponse> => {
  return customFetch<getUiConfigurationApiV1ConfigUiGetResponse>(
    getGetUiConfigurationApiV1ConfigUiGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetUiConfigurationApiV1ConfigUiGetQueryKey = () => {
  return [`/api/v1/config/ui`] as const;
};

export const getGetUiConfigurationApiV1ConfigUiGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUiConfigurationApiV1ConfigUiGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>
  > = ({ signal }) =>
    getUiConfigurationApiV1ConfigUiGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUiConfigurationApiV1ConfigUiGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>
>;
export type GetUiConfigurationApiV1ConfigUiGetQueryError = unknown;

export function useGetUiConfigurationApiV1ConfigUiGet<
  TData = Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
          TError,
          Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUiConfigurationApiV1ConfigUiGet<
  TData = Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
          TError,
          Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUiConfigurationApiV1ConfigUiGet<
  TData = Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Ui Configuration
 */

export function useGetUiConfigurationApiV1ConfigUiGet<
  TData = Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUiConfigurationApiV1ConfigUiGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetUiConfigurationApiV1ConfigUiGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateUiConfigurationApiV1ConfigUiPutResponse200 = {
  data: UIConfiguration;
  status: 200;
};

export type updateUiConfigurationApiV1ConfigUiPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateUiConfigurationApiV1ConfigUiPutResponseSuccess =
  updateUiConfigurationApiV1ConfigUiPutResponse200 & {
    headers: Headers;
  };
export type updateUiConfigurationApiV1ConfigUiPutResponseError =
  updateUiConfigurationApiV1ConfigUiPutResponse422 & {
    headers: Headers;
  };

export type updateUiConfigurationApiV1ConfigUiPutResponse =
  | updateUiConfigurationApiV1ConfigUiPutResponseSuccess
  | updateUiConfigurationApiV1ConfigUiPutResponseError;

export const getUpdateUiConfigurationApiV1ConfigUiPutUrl = () => {
  return `/api/v1/config/ui`;
};

/**
 * Update UI configuration settings (idempotent).
 * @summary Update Ui Configuration
 */
export const updateUiConfigurationApiV1ConfigUiPut = async (
  uIConfigurationUpdate: UIConfigurationUpdate,
  options?: Parameters<typeof customFetch>[1],
): Promise<updateUiConfigurationApiV1ConfigUiPutResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<updateUiConfigurationApiV1ConfigUiPutResponse>(
    getUpdateUiConfigurationApiV1ConfigUiPutUrl(),
    {
      ...options,
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(uIConfigurationUpdate),
    },
  );
};

export const getUpdateUiConfigurationApiV1ConfigUiPutMutationKey = () =>
  ["updateUiConfigurationApiV1ConfigUiPut"] as const;

export const getUpdateUiConfigurationApiV1ConfigUiPutMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>,
    TError,
    UpdateUiConfigurationApiV1ConfigUiPutMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>,
  TError,
  UpdateUiConfigurationApiV1ConfigUiPutMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateUiConfigurationApiV1ConfigUiPutMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>,
    UpdateUiConfigurationApiV1ConfigUiPutMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return updateUiConfigurationApiV1ConfigUiPut(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUiConfigurationApiV1ConfigUiPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>
>;
export type UpdateUiConfigurationApiV1ConfigUiPutMutationBody =
  UIConfigurationUpdate;
export type UpdateUiConfigurationApiV1ConfigUiPutMutationError =
  HTTPValidationError;
export type UpdateUiConfigurationApiV1ConfigUiPutMutationVariables = {
  data: UIConfigurationUpdate;
};

/**
 * @summary Update Ui Configuration
 */
export const useUpdateUiConfigurationApiV1ConfigUiPut = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>,
      TError,
      UpdateUiConfigurationApiV1ConfigUiPutMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUiConfigurationApiV1ConfigUiPut>>,
  TError,
  UpdateUiConfigurationApiV1ConfigUiPutMutationVariables,
  TContext
> => {
  return useMutation(
    getUpdateUiConfigurationApiV1ConfigUiPutMutationOptions(options),
    queryClient,
  );
};
export type patchUiConfigurationApiV1ConfigUiPatchResponse200 = {
  data: UIConfiguration;
  status: 200;
};

export type patchUiConfigurationApiV1ConfigUiPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type patchUiConfigurationApiV1ConfigUiPatchResponseSuccess =
  patchUiConfigurationApiV1ConfigUiPatchResponse200 & {
    headers: Headers;
  };
export type patchUiConfigurationApiV1ConfigUiPatchResponseError =
  patchUiConfigurationApiV1ConfigUiPatchResponse422 & {
    headers: Headers;
  };

export type patchUiConfigurationApiV1ConfigUiPatchResponse =
  | patchUiConfigurationApiV1ConfigUiPatchResponseSuccess
  | patchUiConfigurationApiV1ConfigUiPatchResponseError;

export const getPatchUiConfigurationApiV1ConfigUiPatchUrl = () => {
  return `/api/v1/config/ui`;
};

/**
 * Partially update UI configuration settings.
 * @summary Patch Ui Configuration
 */
export const patchUiConfigurationApiV1ConfigUiPatch = async (
  uIConfigurationUpdate: UIConfigurationUpdate,
  options?: Parameters<typeof customFetch>[1],
): Promise<patchUiConfigurationApiV1ConfigUiPatchResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<patchUiConfigurationApiV1ConfigUiPatchResponse>(
    getPatchUiConfigurationApiV1ConfigUiPatchUrl(),
    {
      ...options,
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(uIConfigurationUpdate),
    },
  );
};

export const getPatchUiConfigurationApiV1ConfigUiPatchMutationKey = () =>
  ["patchUiConfigurationApiV1ConfigUiPatch"] as const;

export const getPatchUiConfigurationApiV1ConfigUiPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>,
    TError,
    PatchUiConfigurationApiV1ConfigUiPatchMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>,
  TError,
  PatchUiConfigurationApiV1ConfigUiPatchMutationVariables,
  TContext
> => {
  const mutationKey = getPatchUiConfigurationApiV1ConfigUiPatchMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>,
    PatchUiConfigurationApiV1ConfigUiPatchMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return patchUiConfigurationApiV1ConfigUiPatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchUiConfigurationApiV1ConfigUiPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>
>;
export type PatchUiConfigurationApiV1ConfigUiPatchMutationBody =
  UIConfigurationUpdate;
export type PatchUiConfigurationApiV1ConfigUiPatchMutationError =
  HTTPValidationError;
export type PatchUiConfigurationApiV1ConfigUiPatchMutationVariables = {
  data: UIConfigurationUpdate;
};

/**
 * @summary Patch Ui Configuration
 */
export const usePatchUiConfigurationApiV1ConfigUiPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>,
      TError,
      PatchUiConfigurationApiV1ConfigUiPatchMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchUiConfigurationApiV1ConfigUiPatch>>,
  TError,
  PatchUiConfigurationApiV1ConfigUiPatchMutationVariables,
  TContext
> => {
  return useMutation(
    getPatchUiConfigurationApiV1ConfigUiPatchMutationOptions(options),
    queryClient,
  );
};
export type detectThemeApiV1ConfigThemeGetResponse200 = {
  data: ThemeDetectionResponse;
  status: 200;
};

export type detectThemeApiV1ConfigThemeGetResponseSuccess =
  detectThemeApiV1ConfigThemeGetResponse200 & {
    headers: Headers;
  };
export type detectThemeApiV1ConfigThemeGetResponse =
  detectThemeApiV1ConfigThemeGetResponseSuccess;

export const getDetectThemeApiV1ConfigThemeGetUrl = () => {
  return `/api/v1/config/theme`;
};

/**
 * Detect and return current theme settings based on context.
 * @summary Detect Theme
 */
export const detectThemeApiV1ConfigThemeGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<detectThemeApiV1ConfigThemeGetResponse> => {
  return customFetch<detectThemeApiV1ConfigThemeGetResponse>(
    getDetectThemeApiV1ConfigThemeGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDetectThemeApiV1ConfigThemeGetQueryKey = () => {
  return [`/api/v1/config/theme`] as const;
};

export const getDetectThemeApiV1ConfigThemeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDetectThemeApiV1ConfigThemeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>
  > = ({ signal }) =>
    detectThemeApiV1ConfigThemeGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DetectThemeApiV1ConfigThemeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>
>;
export type DetectThemeApiV1ConfigThemeGetQueryError = unknown;

export function useDetectThemeApiV1ConfigThemeGet<
  TData = Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
          TError,
          Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetectThemeApiV1ConfigThemeGet<
  TData = Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
          TError,
          Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetectThemeApiV1ConfigThemeGet<
  TData = Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detect Theme
 */

export function useDetectThemeApiV1ConfigThemeGet<
  TData = Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectThemeApiV1ConfigThemeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetectThemeApiV1ConfigThemeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type detectLanguageApiV1ConfigLanguageGetResponse200 = {
  data: LanguageDetectionResponse;
  status: 200;
};

export type detectLanguageApiV1ConfigLanguageGetResponseSuccess =
  detectLanguageApiV1ConfigLanguageGetResponse200 & {
    headers: Headers;
  };
export type detectLanguageApiV1ConfigLanguageGetResponse =
  detectLanguageApiV1ConfigLanguageGetResponseSuccess;

export const getDetectLanguageApiV1ConfigLanguageGetUrl = () => {
  return `/api/v1/config/language`;
};

/**
 * Detect and return current language settings based on context.
 * @summary Detect Language
 */
export const detectLanguageApiV1ConfigLanguageGet = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<detectLanguageApiV1ConfigLanguageGetResponse> => {
  return customFetch<detectLanguageApiV1ConfigLanguageGetResponse>(
    getDetectLanguageApiV1ConfigLanguageGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDetectLanguageApiV1ConfigLanguageGetQueryKey = () => {
  return [`/api/v1/config/language`] as const;
};

export const getDetectLanguageApiV1ConfigLanguageGetQueryOptions = <
  TData = Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDetectLanguageApiV1ConfigLanguageGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>
  > = ({ signal }) =>
    detectLanguageApiV1ConfigLanguageGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DetectLanguageApiV1ConfigLanguageGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>
>;
export type DetectLanguageApiV1ConfigLanguageGetQueryError = unknown;

export function useDetectLanguageApiV1ConfigLanguageGet<
  TData = Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
          TError,
          Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetectLanguageApiV1ConfigLanguageGet<
  TData = Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
          TError,
          Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetectLanguageApiV1ConfigLanguageGet<
  TData = Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detect Language
 */

export function useDetectLanguageApiV1ConfigLanguageGet<
  TData = Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof detectLanguageApiV1ConfigLanguageGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getDetectLanguageApiV1ConfigLanguageGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
