/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DailySummary,
  GetMonthlySummaryApiV1MonthlySummaryGetParams,
  GetWeeklySummaryApiV1WeeklySummaryGetParams,
  HTTPValidationError,
  TodayResponse,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get daily summary for a specific date.
 * @summary Get Daily Summary
 */
export type getDailySummaryApiV1DailySummaryDateGetResponse200 = {
  data: DailySummary;
  status: 200;
};

export type getDailySummaryApiV1DailySummaryDateGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDailySummaryApiV1DailySummaryDateGetResponseSuccess =
  getDailySummaryApiV1DailySummaryDateGetResponse200 & {
    headers: Headers;
  };
export type getDailySummaryApiV1DailySummaryDateGetResponseError =
  getDailySummaryApiV1DailySummaryDateGetResponse422 & {
    headers: Headers;
  };

export type getDailySummaryApiV1DailySummaryDateGetResponse =
  | getDailySummaryApiV1DailySummaryDateGetResponseSuccess
  | getDailySummaryApiV1DailySummaryDateGetResponseError;

export const getGetDailySummaryApiV1DailySummaryDateGetUrl = (date: string) => {
  return `/api/v1/daily-summary/${date}`;
};

export const getDailySummaryApiV1DailySummaryDateGet = async (
  date: string,
  options?: RequestInit,
): Promise<getDailySummaryApiV1DailySummaryDateGetResponse> => {
  return customFetch<getDailySummaryApiV1DailySummaryDateGetResponse>(
    getGetDailySummaryApiV1DailySummaryDateGetUrl(date),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetDailySummaryApiV1DailySummaryDateGetQueryKey = (
  date: string,
) => {
  return [`/api/v1/daily-summary/${date}`] as const;
};

export const getGetDailySummaryApiV1DailySummaryDateGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetDailySummaryApiV1DailySummaryDateGetQueryKey(date);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>
  > = ({ signal }) =>
    getDailySummaryApiV1DailySummaryDateGet(date, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!date,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetDailySummaryApiV1DailySummaryDateGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>
>;
export type GetDailySummaryApiV1DailySummaryDateGetQueryError =
  HTTPValidationError;

export function useGetDailySummaryApiV1DailySummaryDateGet<
  TData = Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
          TError,
          Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetDailySummaryApiV1DailySummaryDateGet<
  TData = Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
          TError,
          Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetDailySummaryApiV1DailySummaryDateGet<
  TData = Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Daily Summary
 */

export function useGetDailySummaryApiV1DailySummaryDateGet<
  TData = Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDailySummaryApiV1DailySummaryDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetDailySummaryApiV1DailySummaryDateGetQueryOptions(
    date,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get weekly summary starting from the given date.
 * @summary Get Weekly Summary
 */
export type getWeeklySummaryApiV1WeeklySummaryGetResponse200 = {
  data: DailySummary[];
  status: 200;
};

export type getWeeklySummaryApiV1WeeklySummaryGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getWeeklySummaryApiV1WeeklySummaryGetResponseSuccess =
  getWeeklySummaryApiV1WeeklySummaryGetResponse200 & {
    headers: Headers;
  };
export type getWeeklySummaryApiV1WeeklySummaryGetResponseError =
  getWeeklySummaryApiV1WeeklySummaryGetResponse422 & {
    headers: Headers;
  };

export type getWeeklySummaryApiV1WeeklySummaryGetResponse =
  | getWeeklySummaryApiV1WeeklySummaryGetResponseSuccess
  | getWeeklySummaryApiV1WeeklySummaryGetResponseError;

export const getGetWeeklySummaryApiV1WeeklySummaryGetUrl = (
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/weekly-summary?${stringifiedParams}`
    : `/api/v1/weekly-summary`;
};

export const getWeeklySummaryApiV1WeeklySummaryGet = async (
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options?: RequestInit,
): Promise<getWeeklySummaryApiV1WeeklySummaryGetResponse> => {
  return customFetch<getWeeklySummaryApiV1WeeklySummaryGetResponse>(
    getGetWeeklySummaryApiV1WeeklySummaryGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetWeeklySummaryApiV1WeeklySummaryGetQueryKey = (
  params?: GetWeeklySummaryApiV1WeeklySummaryGetParams,
) => {
  return [`/api/v1/weekly-summary`, ...(params ? [params] : [])] as const;
};

export const getGetWeeklySummaryApiV1WeeklySummaryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetWeeklySummaryApiV1WeeklySummaryGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>
  > = ({ signal }) =>
    getWeeklySummaryApiV1WeeklySummaryGet(params, {
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetWeeklySummaryApiV1WeeklySummaryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>
>;
export type GetWeeklySummaryApiV1WeeklySummaryGetQueryError =
  HTTPValidationError;

export function useGetWeeklySummaryApiV1WeeklySummaryGet<
  TData = Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetWeeklySummaryApiV1WeeklySummaryGet<
  TData = Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetWeeklySummaryApiV1WeeklySummaryGet<
  TData = Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Weekly Summary
 */

export function useGetWeeklySummaryApiV1WeeklySummaryGet<
  TData = Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetWeeklySummaryApiV1WeeklySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeeklySummaryApiV1WeeklySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetWeeklySummaryApiV1WeeklySummaryGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get monthly summary for the given year and month.
 * @summary Get Monthly Summary
 */
export type getMonthlySummaryApiV1MonthlySummaryGetResponse200 = {
  data: DailySummary[];
  status: 200;
};

export type getMonthlySummaryApiV1MonthlySummaryGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMonthlySummaryApiV1MonthlySummaryGetResponseSuccess =
  getMonthlySummaryApiV1MonthlySummaryGetResponse200 & {
    headers: Headers;
  };
export type getMonthlySummaryApiV1MonthlySummaryGetResponseError =
  getMonthlySummaryApiV1MonthlySummaryGetResponse422 & {
    headers: Headers;
  };

export type getMonthlySummaryApiV1MonthlySummaryGetResponse =
  | getMonthlySummaryApiV1MonthlySummaryGetResponseSuccess
  | getMonthlySummaryApiV1MonthlySummaryGetResponseError;

export const getGetMonthlySummaryApiV1MonthlySummaryGetUrl = (
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/monthly-summary?${stringifiedParams}`
    : `/api/v1/monthly-summary`;
};

export const getMonthlySummaryApiV1MonthlySummaryGet = async (
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options?: RequestInit,
): Promise<getMonthlySummaryApiV1MonthlySummaryGetResponse> => {
  return customFetch<getMonthlySummaryApiV1MonthlySummaryGetResponse>(
    getGetMonthlySummaryApiV1MonthlySummaryGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMonthlySummaryApiV1MonthlySummaryGetQueryKey = (
  params?: GetMonthlySummaryApiV1MonthlySummaryGetParams,
) => {
  return [`/api/v1/monthly-summary`, ...(params ? [params] : [])] as const;
};

export const getGetMonthlySummaryApiV1MonthlySummaryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMonthlySummaryApiV1MonthlySummaryGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>
  > = ({ signal }) =>
    getMonthlySummaryApiV1MonthlySummaryGet(params, {
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetMonthlySummaryApiV1MonthlySummaryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>
>;
export type GetMonthlySummaryApiV1MonthlySummaryGetQueryError =
  HTTPValidationError;

export function useGetMonthlySummaryApiV1MonthlySummaryGet<
  TData = Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetMonthlySummaryApiV1MonthlySummaryGet<
  TData = Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetMonthlySummaryApiV1MonthlySummaryGet<
  TData = Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Monthly Summary
 */

export function useGetMonthlySummaryApiV1MonthlySummaryGet<
  TData = Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
  TError = HTTPValidationError,
>(
  params: GetMonthlySummaryApiV1MonthlySummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlySummaryApiV1MonthlySummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetMonthlySummaryApiV1MonthlySummaryGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get all data needed for the Today page (meals + daily summary) in a single request.
 * @summary Get Today Data
 */
export type getTodayDataApiV1TodayDateGetResponse200 = {
  data: TodayResponse;
  status: 200;
};

export type getTodayDataApiV1TodayDateGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getTodayDataApiV1TodayDateGetResponseSuccess =
  getTodayDataApiV1TodayDateGetResponse200 & {
    headers: Headers;
  };
export type getTodayDataApiV1TodayDateGetResponseError =
  getTodayDataApiV1TodayDateGetResponse422 & {
    headers: Headers;
  };

export type getTodayDataApiV1TodayDateGetResponse =
  | getTodayDataApiV1TodayDateGetResponseSuccess
  | getTodayDataApiV1TodayDateGetResponseError;

export const getGetTodayDataApiV1TodayDateGetUrl = (date: string) => {
  return `/api/v1/today/${date}`;
};

export const getTodayDataApiV1TodayDateGet = async (
  date: string,
  options?: RequestInit,
): Promise<getTodayDataApiV1TodayDateGetResponse> => {
  return customFetch<getTodayDataApiV1TodayDateGetResponse>(
    getGetTodayDataApiV1TodayDateGetUrl(date),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetTodayDataApiV1TodayDateGetQueryKey = (date: string) => {
  return [`/api/v1/today/${date}`] as const;
};

export const getGetTodayDataApiV1TodayDateGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTodayDataApiV1TodayDateGetQueryKey(date);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>
  > = ({ signal }) =>
    getTodayDataApiV1TodayDateGet(date, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!date,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTodayDataApiV1TodayDateGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>
>;
export type GetTodayDataApiV1TodayDateGetQueryError = HTTPValidationError;

export function useGetTodayDataApiV1TodayDateGet<
  TData = Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
          TError,
          Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTodayDataApiV1TodayDateGet<
  TData = Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
          TError,
          Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTodayDataApiV1TodayDateGet<
  TData = Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Today Data
 */

export function useGetTodayDataApiV1TodayDateGet<
  TData = Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
  TError = HTTPValidationError,
>(
  date: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTodayDataApiV1TodayDateGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTodayDataApiV1TodayDateGetQueryOptions(
    date,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}
