/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calories Count API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  MultiPhotoCreateRequest,
  MultiPhotoResponse,
  PhotoCreateRequest,
  PresignResponse,
} from "../../model";

import { customFetch } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type createPhotoApiV1PhotosPostResponse200 = {
  data: PresignResponse | MultiPhotoResponse;
  status: 200;
};

export type createPhotoApiV1PhotosPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createPhotoApiV1PhotosPostResponseSuccess =
  createPhotoApiV1PhotosPostResponse200 & {
    headers: Headers;
  };
export type createPhotoApiV1PhotosPostResponseError =
  createPhotoApiV1PhotosPostResponse422 & {
    headers: Headers;
  };

export type createPhotoApiV1PhotosPostResponse =
  | createPhotoApiV1PhotosPostResponseSuccess
  | createPhotoApiV1PhotosPostResponseError;

export const getCreatePhotoApiV1PhotosPostUrl = () => {
  return `/api/v1/photos`;
};

/**
 * Create photo upload request(s) with support for both single and multi-photo uploads.
 *
 * For single photo: Send {"content_type": "image/jpeg"}
 * For multiple photos: Send {"photos": [{"content_type": "image/jpeg"}, ...]}
 * @summary Create Photo
 */
export const createPhotoApiV1PhotosPost = async (
  photoCreateRequestMultiPhotoCreateRequest:
    | PhotoCreateRequest
    | MultiPhotoCreateRequest,
  options?: Parameters<typeof customFetch>[1],
): Promise<createPhotoApiV1PhotosPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customFetch<createPhotoApiV1PhotosPostResponse>(
    getCreatePhotoApiV1PhotosPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(photoCreateRequestMultiPhotoCreateRequest),
    },
  );
};

export const getCreatePhotoApiV1PhotosPostMutationKey = () =>
  ["createPhotoApiV1PhotosPost"] as const;

export const getCreatePhotoApiV1PhotosPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>,
    TError,
    CreatePhotoApiV1PhotosPostMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>,
  TError,
  CreatePhotoApiV1PhotosPostMutationVariables,
  TContext
> => {
  const mutationKey = getCreatePhotoApiV1PhotosPostMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>,
    CreatePhotoApiV1PhotosPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createPhotoApiV1PhotosPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePhotoApiV1PhotosPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>
>;
export type CreatePhotoApiV1PhotosPostMutationBody =
  | PhotoCreateRequest
  | MultiPhotoCreateRequest;
export type CreatePhotoApiV1PhotosPostMutationError = HTTPValidationError;
export type CreatePhotoApiV1PhotosPostMutationVariables = {
  data: PhotoCreateRequest | MultiPhotoCreateRequest;
};

/**
 * @summary Create Photo
 */
export const useCreatePhotoApiV1PhotosPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>,
      TError,
      CreatePhotoApiV1PhotosPostMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPhotoApiV1PhotosPost>>,
  TError,
  CreatePhotoApiV1PhotosPostMutationVariables,
  TContext
> => {
  return useMutation(
    getCreatePhotoApiV1PhotosPostMutationOptions(options),
    queryClient,
  );
};
