name: Backend Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
    tags: [ 'v*' ]

defaults:
  run:
    working-directory: backend

jobs:
  fly-deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Deploy to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --image ghcr.io/${{ github.repository }}:latest
