name: Backend Build
on:
  workflow_run:
    workflows: ["Backend CI"]
    types: [completed]
    branches: [ main ]
  push:
    tags: [ 'v*' ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-build.yml'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
