name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    name: tests & lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: .python-version

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.15"

    - name: Sync deps
      run: uv sync --all-extras

    - name: Ruff lint
      run: uv run ruff check .

    - name: Ruff format (check)
      run: uv run ruff format --check .

    - name: Pyright
      run: uv run pyright

    - name: Pytest
      run: uv run pytest -q
      env:
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_KEY: test-supabase-key
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REDIS_URL: redis://localhost:6379
        AWS_ENDPOINT_URL_S3: https://test.tigris.com
        AWS_ACCESS_KEY_ID: test-access-key
        AWS_SECRET_ACCESS_KEY: test-secret-key
        BUCKET_NAME: test-bucket
        AWS_REGION: auto
